# Project Python Foundations: FoodHub Data Analysis

### Context

The number of restaurants in New York is increasing day by day. Lots of students and busy professionals rely on those restaurants due to their hectic lifestyles. Online food delivery service is a great option for them. It provides them with good food from their favorite restaurants. A food aggregator company FoodHub offers access to multiple restaurants through a single smartphone app.

The app allows the restaurants to receive a direct online order from a customer. The app assigns a delivery person from the company to pick up the order after it is confirmed by the restaurant. The delivery person then uses the map to reach the restaurant and waits for the food package. Once the food package is handed over to the delivery person, he/she confirms the pick-up in the app and travels to the customer's location to deliver the food. The delivery person confirms the drop-off in the app after delivering the food package to the customer. The customer can rate the order in the app. The food aggregator earns money by collecting a fixed margin of the delivery order from the restaurants.

### Objective

The food aggregator company has stored the data of the different orders made by the registered customers in their online portal. They want to analyze the data to get a fair idea about the demand of different restaurants which will help them in enhancing their customer experience. Suppose you are hired as a Data Scientist in this company and the Data Science team has shared some of the key questions that need to be answered. Perform the data analysis to find answers to these questions that will help the company to improve the business.

### Data Description

The data contains the different data related to a food order. The detailed data dictionary is given below.

### Data Dictionary

* order_id: Unique ID of the order
* customer_id: ID of the customer who ordered the food
* restaurant_name: Name of the restaurant
* cuisine_type: Cuisine ordered by the customer
* cost_of_the_order: Cost of the order
* day_of_the_week: Indicates whether the order is placed on a weekday or weekend (The weekday is from Monday to Friday and the weekend is Saturday and Sunday)
* rating: Rating given by the customer out of 5
* food_preparation_time: Time (in minutes) taken by the restaurant to prepare the food. This is calculated by taking the difference between the timestamps of the restaurant's order confirmation and the delivery person's pick-up confirmation.
* delivery_time: Time (in minutes) taken by the delivery person to deliver the food package. This is calculated by taking the difference between the timestamps of the delivery person's pick-up confirmation and drop-off information

### Let us start by importing the required libraries

In [12]:
# Installing the libraries with the specified version.
!pip install numpy==2.0.2 pandas==2.2.2 matplotlib==3.10.0 seaborn==0.13.2 -q --user

ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

**Note**:
- After running the above cell, kindly restart the runtime (for Google Colab) or notebook kernel (for Jupyter Notebook), and run all cells sequentially from the next cell.
- On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in ***this notebook***.

In [13]:
# import libraries for data manipulation
import numpy as np
import pandas as pd

# import libraries for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib'

### Understanding the structure of the data

In [ ]:
# uncomment and run the below code snippets if the dataset is present in the Google Drive
# from google.colab import drive
# drive.mount('/content/drive')

In [27]:
# Write your code here to read the data
import pandas as pd
df = pd.read_csv('foodhub_order.csv')
pd.set_option('display.max_rows', None)
print(df)

      order_id  customer_id                        restaurant_name  \
0      1477147       337525                                Hangawi
1      1477685       358141              Blue Ribbon Sushi Izakaya
2      1477070        66393                            Cafe Habana
3      1477334       106968              Blue Ribbon Fried Chicken
4      1478249        76942                       Dirty Bird to Go
5      1477224       147468                       Tamarind TriBeCa
6      1477894       157711                      The Meatball Shop
7      1477859        89574                              Barbounia
8      1477174       121706                     Anjappar Chettinad
9      1477311        39705                          Bukhara Grill
10     1477895       143926             Big Wong Restaurant _¤¾Ñ¼
11     1478437       221206                 Empanada Mama (closed)
12     1476966       129969              Blue Ribbon Fried Chicken
13     1477449       104548                                  Pylos
14     1478198        62667                 Lucky's Famous Burgers
15     1477414        66222                            Shake Shack
16     1477486       104555                          Sushi of Gari
17     1477373       139885              Blue Ribbon Sushi Izakaya
18     1477138        47280                         RedFarm Hudson
19     1477354        67487                      Blue Ribbon Sushi
20     1478296       250494            Five Guys Burgers and Fries
21     1478226       137565                            Shake Shack
22     1478287       150599                            Shake Shack
23     1478014        54630                               Tortaria
24     1476714       363783                           Cafe Mogador
25     1476693        41877                           Cafe Mogador
26     1476995       371590                      The Meatball Shop
27     1476844       175290                  Otto Enoteca Pizzeria
28     1477015        76686                 Vezzo Thin Crust Pizza
29     1476889       149984                       Sushi of Gari 46
30     1478289       318874                  The Kati Roll Company
31     1477699       302790                                  Klong
32     1476855       317794                        5 Napkin Burger
33     1477748       105349                                    TAO
34     1478244       181782                                   Parm
35     1478310        65224                            Sushi Samba
36     1478017       148649                      Blue Ribbon Sushi
37     1476871       118709                      The Meatball Shop
38     1477999       208020                     Haru Gramercy Park
39     1476891       220693                            Shake Shack
40     1477425       378482  Chipotle Mexican Grill $1.99 Delivery
41     1478143       337525                                    TAO
42     1477267       133637                       RedFarm Broadway
43     1477728       107909                              Cafeteria
44     1476908       365237            Five Guys Burgers and Fries
45     1476581       322162                      The Meatball Shop
46     1476930       198802                          DuMont Burger
47     1477621       122864                        Sarabeth's East
48     1478354        52037              Blue Ribbon Fried Chicken
49     1477251        81110             Hill Country Fried Chicken
50     1477656       300003                               Bistango
51     1477883        91817              Blue Ribbon Fried Chicken
52     1477205       112036                                    TAO
53     1478107        73895                       RedFarm Broadway
54     1477760       130507                      Jack's Wife Freda
55     1476562       129486                       Mamoun's Falafel
56     1477692       313340                       Sushi of Gari 46
57     1477889       177250                         RedFarm Hudson
58     1477243       176234                    Prosperity Dumpling
59     1477560       371677              Blue Ribbon Fried Chicken
60     1476896       388918              Blue Ribbon Fried Chicken
61     1478327        68551          Blue Ribbon Sushi Bar & Grill
62     1476820       152786                            Cafe Habana
63     1478121        62980                       Westville Hudson
64     1478077        82041                            Shake Shack
65     1478359       361616                   Blue Ribbon Brooklyn
66     1476841       398426                       RedFarm Broadway
67     1477125       130820                         Nobu Next Door
68     1477915       200074                         Osteria Morini
69     1477475        65009              Blue Ribbon Fried Chicken
70     1477932       170221                            Shake Shack
71     1476651        58092                            Shake Shack
72     1477730        50616                                   Parm
73     1477518       133202                            Sushi Samba
74     1477821       277898                                 Haandi
75     1477104        77341                      The Meatball Shop
76     1477921        97079                               Benihana
77     1477938       150002                  The Kati Roll Company
78     1476943        87472                         RedFarm Hudson
79     1477581       231061                            Han Dynasty
80     1477975        56722                            Shake Shack
81     1477601       107909                              Cafeteria
82     1477790       133617                            Shake Shack
83     1477385        67538  Chipotle Mexican Grill $1.99 Delivery
84     1478423       129969                      The Meatball Shop
85     1477051        57174                               Tortaria
86     1476796        78939                         Nobu Next Door
87     1478031       309513                  Otto Enoteca Pizzeria
88     1477740       129798                                    TAO
89     1478384       184085             Hill Country Fried Chicken
90     1478183       329710                            Shake Shack
91     1477569        65009                            Chote Nawab
92     1478211       154030                         RedFarm Hudson
93     1476635        86731                        Mission Cantina
94     1477646       306119                     Xi'an Famous Foods
95     1477027       164016              Blue Ribbon Fried Chicken
96     1476921       121476              Blue Ribbon Fried Chicken
97     1476689       305522                            Shake Shack
98     1477767        68976                        Sarabeth's East
99     1476582        60703                            Cafe Habana
100    1478169        80460                               Rubirosa
101    1477702       128600              Blue Ribbon Fried Chicken
102    1477240       142356                      Blue Ribbon Sushi
103    1476564        83287            Five Guys Burgers and Fries
104    1478408       134152                      The Meatball Shop
105    1477824       345899                                    TAO
106    1477617        38050                      Blue Ribbon Sushi
107    1477978       259341               Joe's Shanghai _Àü£¾÷´
108    1477281       309513                  Otto Enoteca Pizzeria
109    1478223       234089                      Blue Ribbon Sushi
110    1477364       125123                            Shake Shack
111    1476715       365244                             Bareburger
112    1476654        63020                              The Odeon
113    1477296       222879                                   Parm
114    1478321       275535                           Pongsri Thai
115    1477942        49793               Yama Japanese Restaurant
116    1477552       137565                            Shake Shack
117    1476770        65009              Blue Ribbon Fried Chicken
118    1476558       214394               Yama Japanese Restaurant
119    1477993        91907                                 Momoya
120    1478072        82041                         Osteria Morini
121    1476935        59419              Blue Ribbon Fried Chicken
122    1477255        50199            Five Guys Burgers and Fries
123    1477012       325210                      The Meatball Shop
124    1477704       100999                  Balthazar Boulangerie
125    1477188       146588                          Sushi of Gari
126    1478348       310051                                   Parm
127    1477405       128243                      The Meatball Shop
128    1476826        53543                            CafÌ© China
129    1478340       230535                            Shake Shack
130    1477044       127122                       RedFarm Broadway
131    1476978       177250                         RedFarm Hudson
132    1477287       111125                  Otto Enoteca Pizzeria
133    1477110       144997                         RedFarm Hudson
134    1476555        97991          Blue Ribbon Sushi Bar & Grill
135    1476862        58533                      The Meatball Shop
136    1477117       104336                         Nobu Next Door
137    1478402       232582                            CafÌ© China
138    1477431       195927                               Boqueria
139    1477836       373689                             Bareburger
140    1477376       370372              Blue Ribbon Fried Chicken
141    1476835       264707                                    TAO
142    1477177        42385             Song Thai Restaurant & Bar
143    1478174       104555                          Sushi of Gari
144    1478269       250494                      The Meatball Shop
145    1477369       139085                            Shake Shack
146    1476969       198309                      Blue Ribbon Sushi
147    1477420       399478                            Shake Shack
148    1476663        40010                                   Parm
149    1477904        48131                         RedFarm Hudson
150    1478219        41692                            Shake Shack
151    1477206        61305          Blue Ribbon Sushi Bar & Grill
152    1477337       123780            Five Guys Burgers and Fries
153    1476809       385248                            Shake Shack
154    1477750        97806                            Shake Shack
155    1476817        97079                               Benihana
156    1476659        52463                       RedFarm Broadway
157    1477609       105068                                    TAO
158    1477616       128600                       Tamarind TriBeCa
159    1476769        71791                       Sushi of Gari 46
160    1477185       362068                  The Kati Roll Company
161    1477752       298824                            Shake Shack
162    1477239        94524                      The Meatball Shop
163    1476590       342107                  The Kati Roll Company
164    1478305        62359                               Rubirosa
165    1476751       347181                      Blue Ribbon Sushi
166    1477831        60052                       RedFarm Broadway
167    1477955       198936                            Five Leaves
168    1476568       348787                  Otto Enoteca Pizzeria
169    1478391       184325              Pinto Nouveau Thai Bistro
170    1476725        42935                              Barbounia
171    1476688       200672                           Cafe Mogador
172    1477102        75484            Five Guys Burgers and Fries
173    1476878       378027                       RedFarm Broadway
174    1476805        93133                                   Parm
175    1478093       268958                              Barbounia
176    1478201       370017                       RedFarm Broadway
177    1478032       146586                       Dirty Bird to Go
178    1476606       350085                      The Meatball Shop
179    1477570       292343                             Amy Ruth's
180    1476808        84700                            Pepe Giallo
181    1476610        53212                                    TAO
182    1476875       373353                              indikitch
183    1476829        79255                      The Meatball Shop
184    1477366       275689                            Han Dynasty
185    1477774       354719                      The Meatball Shop
186    1477209        17495                    Prosperity Dumpling
187    1478334       352247  Chipotle Mexican Grill $1.99 Delivery
188    1477872       300670                            Shake Shack
189    1478417        87747              Blue Ribbon Fried Chicken
190    1477401       326426                          Sushi of Gari
191    1477764       131645                                Yama 49
192    1477835       129518              Blue Ribbon Fried Chicken
193    1476997       103005               Yama Japanese Restaurant
194    1477519       140477                                 Momoya
195    1477004       250494            Five Guys Burgers and Fries
196    1477536       105164                         Piccolo Angolo
197    1478313       160957                                 Momoya
198    1477290       361509                            Shake Shack
199    1476648       169478                       RedFarm Broadway
200    1476657        91192             Hill Country Fried Chicken
201    1478089       134294                            Shake Shack
202    1478026       365225                       Pepe Rosso To Go
203    1477768       279895                            Shake Shack
204    1477424        81110                            Han Dynasty
205    1478378       384391                            Shake Shack
206    1477493       328357                            Shake Shack
207    1478092        41318                      Jack's Wife Freda
208    1477150        92832            Five Guys Burgers and Fries
209    1478157        58871                            Shake Shack
210    1478343       231042                                 Momoya
211    1476860       336162                         Nobu Next Door
212    1477675        76907                            Han Dynasty
213    1476799       389740                              L'Express
214    1476598        41168                                   Parm
215    1477277        59749                             Bareburger
216    1476682        86731                        Mission Cantina
217    1477047        42832                        5 Napkin Burger
218    1478173        91005                            Han Dynasty
219    1477528       128963                            Han Dynasty
220    1478426       124085          Blue Ribbon Sushi Bar & Grill
221    1476696       231061                            Han Dynasty
222    1478189       105138                            Han Dynasty
223    1477532        95164                                   Amma
224    1477324       263426              Blue Ribbon Sushi Izakaya
225    1476698       142461                           Delicatessen
226    1478290       263199                       Sushi of Gari 46
227    1476919       387227          Blue Ribbon Sushi Bar & Grill
228    1477247       385559              Blue Ribbon Fried Chicken
229    1477794       127149                        Sarabeth's East
230    1477048       200074                         Osteria Morini
231    1477615       136876                               Rubirosa
232    1476566       103884                                  S'MAC
233    1477310        38612                    Vanessa's Dumplings
234    1477758       334619              Blue Ribbon Sushi Izakaya
235    1477765        92996                       Tamarind TriBeCa
236    1476753       195723                            Cafe Habana
237    1476759       268958                       Sushi of Gari 46
238    1477333       111356                    Bhatti Indian Grill
239    1476830       361509                              Cafeteria
240    1478227       367591                             Taro Sushi
241    1476789       103005               Yama Japanese Restaurant
242    1477603       399121                      Blue Ribbon Sushi
243    1478246       260680                           Delicatessen
244    1476931       124838             Hill Country Fried Chicken
245    1477029       295111                      The Meatball Shop
246    1476849        42052                       Pepe Rosso To Go
247    1478179        52832                            Han Dynasty
248    1477679       120833                             Bareburger
249    1477810        94483                               Bistango
250    1477342        49631                      The Meatball Shop
251    1478133       114085          Blue Ribbon Sushi Bar & Grill
252    1477756       251607                            Shake Shack
253    1477721        72339                             Donburi-ya
254    1476952       229946                  Balthazar Boulangerie
255    1477587        92726                              Hatsuhana
256    1478210       320493                    Vanessa's Dumplings
257    1477887        69348                       RedFarm Broadway
258    1478366       270149                           Samurai Mama
259    1478279       354016                          Waverly Diner
260    1476819       104548           Tarallucci e Vino Restaurant
261    1477394       105754                                 Momoya
262    1476667       157578                          P.J. Clarke's
263    1476975       350373              Blue Ribbon Fried Chicken
264    1477909        47440              Blue Ribbon Fried Chicken
265    1476579        85633                      The Meatball Shop
266    1477286       110091                      The Meatball Shop
267    1478436        95164                                   Amma
268    1476685        96877                      The Meatball Shop
269    1477912       261400                      The Meatball Shop
270    1476892       177078                   Lantern Thai Kitchen
271    1476882        68429                            Shake Shack
272    1477314        52832                       ilili Restaurant
273    1477712       373633                                Yama 49
274    1477057       390490                   Blue Ribbon Brooklyn
275    1477926        72639                          P.J. Clarke's
276    1477273        95644                       RedFarm Broadway
277    1478003       129597                  Otto Enoteca Pizzeria
278    1477522       101084                         RedFarm Hudson
279    1476947        46859                      The Meatball Shop
280    1478295       117810                                 Momoya
281    1476551        49034                              The Smile
282    1476846        82041                                   Parm
283    1476974       142461                            Shake Shack
284    1478005        97991          Blue Ribbon Sushi Bar & Grill
285    1476653       113972                         RedFarm Hudson
286    1476563       114085          Blue Ribbon Sushi Bar & Grill
287    1478440       231042                                 Momoya
288    1477348       298824                             Bareburger
289    1477525        52360                                    TAO
290    1477920        83504                  Balthazar Boulangerie
291    1477797       194778                            Shake Shack
292    1477640       105992                       RedFarm Broadway
293    1477091       373486  Chipotle Mexican Grill $1.99 Delivery
294    1477010        49631                      The Meatball Shop
295    1478324       250494              Blue Ribbon Fried Chicken
296    1477908       378923               Vanessa's Dumpling House

In [ ]:
# Write your code here to view the first 5 rows
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24

### **Question 1:** How many rows and columns are present in the data? [0.5 mark]

In [24]:
# Write your code here
len(df.columns)

9

In [23]:
len(df.index)

1898

#### Observations:

### **Question 2:** What are the datatypes of the different columns in the dataset? (The info() function can be used) [0.5 mark]

In [25]:
# Write your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1898 entries, 0 to 1897
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1898 non-null   int64
 1   customer_id            1898 non-null   int64
 2   restaurant_name        1898 non-null   object
 3   cuisine_type           1898 non-null   object
 4   cost_of_the_order      1898 non-null   float64
 5   day_of_the_week        1898 non-null   object
 6   rating                 1898 non-null   object
 7   food_preparation_time  1898 non-null   int64
 8   delivery_time          1898 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 133.6+ KB

#### Observations:

### **Question 3:** Are there any missing values in the data? If yes, treat them using an appropriate method. [1 mark]

In [30]:
# Write your code here
df.isna()

      order_id  customer_id  restaurant_name  cuisine_type  cost_of_the_order  \
0        False        False            False         False              False
1        False        False            False         False              False
2        False        False            False         False              False
3        False        False            False         False              False
4        False        False            False         False              False
5        False        False            False         False              False
6        False        False            False         False              False
7        False        False            False         False              False
8        False        False            False         False              False
9        False        False            False         False              False
10       False        False            False         False              False
11       False        False            False         False              False
12       False        False            False         False              False
13       False        False            False         False              False
14       False        False            False         False              False
15       False        False            False         False              False
16       False        False            False         False              False
17       False        False            False         False              False
18       False        False            False         False              False
19       False        False            False         False              False
20       False        False            False         False              False
21       False        False            False         False              False
22       False        False            False         False              False
23       False        False            False         False              False
24       False        False            False         False              False
25       False        False            False         False              False
26       False        False            False         False              False
27       False        False            False         False              False
28       False        False            False         False              False
29       False        False            False         False              False
30       False        False            False         False              False
31       False        False            False         False              False
32       False        False            False         False              False
33       False        False            False         False              False
34       False        False            False         False              False
35       False        False            False         False              False
36       False        False            False         False              False
37       False        False            False         False              False
38       False        False            False         False              False
39       False        False            False         False              False
40       False        False            False         False              False
41       False        False            False         False              False
42       False        False            False         False              False
43       False        False            False         False              False
44       False        False            False         False              False
45       False        False            False         False              False
46       False        False            False         False              False
47       False        False            False         False              False
48       False        False            False         False              False
49       False        False            False         False              False
50       False        False            False         False              False
51       False        False            False         False              False
52       False        False            False         False              False
53       False        False            False         False              False
54       False        False            False         False              False
55       False        False            False         False              False
56       False        False            False         False              False
57       False        False            False         False              False
58       False        False            False         False              False
59       False        False            False         False              False
60       False        False            False         False              False
61       False        False            False         False              False
62       False        False            False         False              False
63       False        False            False         False              False
64       False        False            False         False              False
65       False        False            False         False              False
66       False        False            False         False              False
67       False        False            False         False              False
68       False        False            False         False              False
69       False        False            False         False              False
70       False        False            False         False              False
71       False        False            False         False              False
72       False        False            False         False              False
73       False        False            False         False              False
74       False        False            False         False              False
75       False        False            False         False              False
76       False        False            False         False              False
77       False        False            False         False              False
78       False        False            False         False              False
79       False        False            False         False              False
80       False        False            False         False              False
81       False        False            False         False              False
82       False        False            False         False              False
83       False        False            False         False              False
84       False        False            False         False              False
85       False        False            False         False              False
86       False        False            False         False              False
87       False        False            False         False              False
88       False        False            False         False              False
89       False        False            False         False              False
90       False        False            False         False              False
91       False        False            False         False              False
92       False        False            False         False              False
93       False        False            False         False              False
94       False        False            False         False              False
95       False        False            False         False              False
96       False        False            False         False              False
97       False        False            False         False              False
98       False        False            False         False              False
99       False        False            False         False              False
100      False        False            False         False              False
101      False        False            False         False              False
102      False        False            False         False              False
103      False        False            False         False              False
104      False        False            False         False              False
105      False        False            False         False              False
106      False        False            False         False              False
107      False        False            False         False              False
108      False        False            False         False              False
109      False        False            False         False              False
110      False        False            False         False              False
111      False        False            False         False              False
112      False        False            False         False              False
113      False        False            False         False              False
114      False        False            False         False              False
115      False        False            False         False              False
116      False        False            False         False              False
117      False        False            False         False              False
118      False        False            False         False              False
119      False        False            False         False              False
120      False        False            False         False              False
121      False        False            False         False              False
122      False        False            False         False              False
123      False        False            False         False              False
124      False        False            False         False              False
125      False        False            False         False              False
126      False        False            False         False              False
127      False        False            False         False              False
128      False        False            False         False              False
129      False        False            False         False              False
130      False        False            False         False              False
131      False        False            False         False              False
132      False        False            False         False              False
133      False        False            False         False              False
134      False        False            False         False              False
135      False        False            False         False              False
136      False        False            False         False              False
137      False        False            False         False              False
138      False        False            False         False              False
139      False        False            False         False              False
140      False        False            False         False              False
141      False        False            False         False              False
142      False        False            False         False              False
143      False        False            False         False              False
144      False        False            False         False              False
145      False        False            False         False              False
146      False        False            False         False              False
147      False        False            False         False              False
148      False        False            False         False              False
149      False        False            False         False              False
150      False        False            False         False              False
151      False        False            False         False              False
152      False        False            False         False              False
153      False        False            False         False              False
154      False        False            False         False              False
155      False        False            False         False              False
156      False        False            False         False              False
157      False        False            False         False              False
158      False        False            False         False              False
159      False        False            False         False              False
160      False        False            False         False              False
161      False        False            False         False              False
162      False        False            False         False              False
163      False        False            False         False              False
164      False        False            False         False              False
165      False        False            False         False              False
166      False        False            False         False              False
167      False        False            False         False              False
168      False        False            False         False              False
169      False        False            False         False              False
170      False        False            False         False              False
171      False        False            False         False              False
172      False        False            False         False              False
173      False        False            False         False              False
174      False        False            False         False              False
175      False        False            False         False              False
176      False        False            False         False              False
177      False        False            False         False              False
178      False        False            False         False              False
179      False        False            False         False              False
180      False        False            False         False              False
181      False        False            False         False              False
182      False        False            False         False              False
183      False        False            False         False              False
184      False        False            False         False              False
185      False        False            False         False              False
186      False        False            False         False              False
187      False        False            False         False              False
188      False        False            False         False              False
189      False        False            False         False              False
190      False        False            False         False              False
191      False        False            False         False              False
192      False        False            False         False              False
193      False        False            False         False              False
194      False        False            False         False              False
195      False        False            False         False              False
196      False        False            False         False              False
197      False        False            False         False              False
198      False        False            False         False              False
199      False        False            False         False              False
200      False        False            False         False              False
201      False        False            False         False              False
202      False        False            False         False              False
203      False        False            False         False              False
204      False        False            False         False              False
205      False        False            False         False              False
206      False        False            False         False              False
207      False        False            False         False              False
208      False        False            False         False              False
209      False        False            False         False              False
210      False        False            False         False              False
211      False        False            False         False              False
212      False        False            False         False              False
213      False        False            False         False              False
214      False        False            False         False              False
215      False        False            False         False              False
216      False        False            False         False              False
217      False        False            False         False              False
218      False        False            False         False              False
219      False        False            False         False              False
220      False        False            False         False              False
221      False        False            False         False              False
222      False        False            False         False              False
223      False        False            False         False              False
224      False        False            False         False              False
225      False        False            False         False              False
226      False        False            False         False              False
227      False        False            False         False              False
228      False        False            False         False              False
229      False        False            False         False              False
230      False        False            False         False              False
231      False        False            False         False              False
232      False        False            False         False              False
233      False        False            False         False              False
234      False        False            False         False              False
235      False        False            False         False              False
236      False        False            False         False              False
237      False        False            False         False              False
238      False        False            False         False              False
239      False        False            False         False              False
240      False        False            False         False              False
241      False        False            False         False              False
242      False        False            False         False              False
243      False        False            False         False              False
244      False        False            False         False              False
245      False        False            False         False              False
246      False        False            False         False              False
247      False        False            False         False              False
248      False        False            False         False              False
249      False        False            False         False              False
250      False        False            False         False              False
251      False        False            False         False              False
252      False        False            False         False              False
253      False        False            False         False              False
254      False        False            False         False              False

#### Observations:

### **Question 4:** Check the statistical summary of the data. What is the minimum, average, and maximum time it takes for food to be prepared once an order is placed? [2 marks]

In [36]:
# Write your code here
print(df["food_preparation_time"].max())

35

In [37]:
print(df["food_preparation_time"].min())

20

In [38]:
print(df["food_preparation_time"].mean())

27.371970495258168

#### Observations:

### **Question 5:** How many orders are not rated? [1 mark]

In [53]:
pd.set_option('display.max_rows', None)
df[df["rating"] == "Not given"]

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23
6,1477894,157711,The Meatball Shop,Italian,6.07,Weekend,Not given,28,21
10,1477895,143926,Big Wong Restaurant _¤¾Ñ¼,Chinese,5.92,Weekday,Not given,34,28
14,1478198,62667,Lucky's Famous Burgers,American,12.13,Weekday,Not given,23,30
16,1477486,104555,Sushi of Gari,Japanese,16.98,Weekend,Not given,30,16
17,1477373,139885,Blue Ribbon Sushi Izakaya,Japanese,33.03,Weekend,Not given,21,22
21,1478226,137565,Shake Shack,American,15.91,Weekend,Not given,25,20
23,1478014,54630,Tortaria,Mexican,8.92,Weekend,Not given,33,16
24,1476714,363783,Cafe Mogador,Middle Eastern,15.86,Weekday,Not given,32,29
27,1476844,175290,Otto Enoteca Pizzeria,Italian,14.02,Weekend,Not given,24,16
28,1477015,76686,Vezzo Thin Crust Pizza,Italian,9.17,Weekend,Not given,21,24
29,1476889,149984,Sushi of Gari 46,Japanese,12.18,Weekday,Not given,20,29
32,1476855,317794,5 Napkin Burger,American,8.39,Weekday,Not given,35,24
33,1477748,105349,TAO,Japanese,9.12,Weekend,Not given,34,18
35,1478310,65224,Sushi Samba,Japanese,15.47,Weekend,Not given,32,26
39,1476891,220693,Shake Shack,American,19.89,Weekend,Not given,27,19
41,1478143,337525,TAO,Japanese,33.22,Weekend,Not given,23,19
43,1477728,107909,Cafeteria,American,16.44,Weekend,Not given,33,22
48,1478354,52037,Blue Ribbon Fried Chicken,American,19.89,Weekday,Not given,27,24
50,1477656,300003,Bistango,Italian,21.88,Weekend,Not given,21,19
51,1477883,91817,Blue Ribbon Fried Chicken,American,29.39,Weekend,Not given,27,28
53,1478107,73895,RedFarm Broadway,Chinese,29.10,Weekend,Not given,22,23
59,1477560,371677,Blue Ribbon Fried Chicken,American,6.79,Weekday,Not given,33,28
60,1476896,388918,Blue Ribbon Fried Chicken,American,24.25,Weekend,Not given,28,21
61,1478327,68551,Blue Ribbon Sushi Bar & Grill,Japanese,33.03,Weekend,Not given,33,20
63,1478121,62980,Westville Hudson,American,8.34,Weekday,Not given,22,26
64,1478077,82041,Shake Shack,American,33.03,Weekday,Not given,22,32
68,1477915,200074,Osteria Morini,Italian,14.55,Weekend,Not given,34,22
70,1477932,170221,Shake Shack,American,16.98,Weekend,Not given,22,21
72,1477730,50616,Parm,Italian,13.05,Weekend,Not given,28,27
75,1477104,77341,The Meatball Shop,Italian,16.93,Weekend,Not given,30,25
78,1476943,87472,RedFarm Hudson,Chinese,22.75,Weekend,Not given,31,30
84,1478423,129969,The Meatball Shop,Italian,21.20,Weekend,Not given,34,16
85,1477051,57174,Tortaria,Mexican,19.31,Weekend,Not given,27,28
94,1477646,306119,Xi'an Famous Foods,Chinese,9.22,Weekday,Not given,31,32
95,1477027,164016,Blue Ribbon Fried Chicken,American,16.39,Weekend,Not given,27,22
99,1476582,60703,Cafe Habana,Mexican,6.79,Weekday,Not given,33,25
101,1477702,128600,Blue Ribbon Fried Chicken,American,31.29,Weekday,Not given,22,33
104,1478408,134152,The Meatball Shop,Italian,22.26,Weekend,Not given,28,25
110,1477364,125123,Shake Shack,American,21.83,Weekend,Not given,23,22
111,1476715,365244,Bareburger,American,16.30,Weekday,Not given,20,28
116,1477552,137565,Shake Shack,American,31.29,Weekday,Not given,26,32
118,1476558,214394,Yama Japanese Restaurant,Japanese,16.10,Weekend,Not given,33,27
122,1477255,50199,Five Guys Burgers and Fries,American,12.13,Weekend,Not given,26,15
123,1477012,325210,The Meatball Shop,American,12.32,Weekend,Not given,31,19
124,1477704,100999,Balthazar Boulangerie,French,12.13,Weekend,Not given,22,27
126,1478348,310051,Parm,Italian,14.99,Weekend,Not given,34,24
128,1476826,53543,CafÌ© China,Chinese,24.30,Weekend,Not given,20,23
131,1476978,177250,RedFarm Hudson,Chinese,25.27,Weekend,Not given,34,28
132,1477287,111125,Otto Enoteca Pizzeria,Italian,14.99,Weekend,Not given,29,21
134,1476555,97991,Blue Ribbon Sushi Bar & Grill,Japanese,9.65,Weekend,Not given,25,26
135,1476862,58533,The Meatball Shop,Italian,29.20,Weekend,Not given,31,24
139,1477836,373689,Bareburger,American,12.08,Weekend,Not given,29,20
140,1477376,370372,Blue Ribbon Fried Chicken,American,11.59,Weekday,Not given,25,24
143,1478174,104555,Sushi of Gari,Japanese,29.34,Weekday,Not given,32,25
145,1477369,139085,Shake Shack,American,24.25,Weekday,Not given,32,24
146,1476969,198309,Blue Ribbon Sushi,Japanese,29.20,Weekend,Not given,22,25
147,1477420,399478,Shake Shack,American,14.07,Weekend,Not given,25,28
150,1478219,41692,Shake Shack,American,22.80,Weekend,Not given,30,19
151,1477206,61305,Blue Ribbon Sushi Bar & Grill,Japanese,15.23,Weekend,Not given,30,19
152,1477337,123780,Five Guys Burgers and Fries,American,33.03,Weekend,Not given,29,25
153,1476809,385248,Shake Shack,American,12.95,Weekend,Not given,27,18
155,1476817,97079,Benihana,Japanese,29.05,Weekend,Not given,25,26
157,1477609,105068,TAO,Japanese,16.01,Weekend,Not given,26,16
159,1476769,71791,Sushi of Gari 46,Japanese,8.83,Weekday,Not given,31,33
160,1477185,362068,The Kati Roll Company,Indian,33.03,Weekend,Not given,35,21
165,1476751,347181,Blue Ribbon Sushi,Japanese,16.01,Weekend,Not given,29,22
167,1477955,198936,Five Leaves,American,10.24,Weekday,Not given,22,25
171,1476688,200672,Cafe Mogador,Middle Eastern,13.00,Weekend,Not given,21,15
172,1477102,75484,Five Guys Burgers and Fries,American,13.05,Weekend,Not given,34,27
173,1476878,378027,RedFarm Broadway,Chinese,8.49,Weekend,Not given,24,16
178,1476606,350085,The Meatball Shop,Italian,17.03,Weekday,Not given,22,29
181,1476610,53212,TAO,Japanese,12.27,Weekday,Not given,26,29
182,1476875,373353,indikitch,Indian,22.26,Weekend,Not given,35,16
183,1476829,79255,The Meatball Shop,Italian,6.79,Weekend,Not given,26,15
186,1477209,17495,Prosperity Dumpling,Chinese,12.18,Weekday,Not given,26,24
188,1477872,300670,Shake Shack,American,13.39,Weekend,Not given,30,22
190,1477401,326426,Sushi of Gari,Japanese,29.15,Weekend,Not given,34,24
194,1477519,140477,Momoya,Japanese,31.43,Weekend,Not given,24,17
198,1477290,361509,Shake Shack,American,19.35,Weekday,Not given,35,33
199,1476648,169478,RedFarm Broadway,Chinese,19.35,Weekend,Not given,24,28
204,1477424,81110,Han Dynasty,Chinese,12.95,Weekend,Not given,20,25
215,1477277,59749,Bareburger,American,16.49,Weekday,Not given,31,27
216,1476682,86731,Mission Cantina,Mexican,12.08,Weekend,Not given,30,18
217,1477047,42832,5 Napkin Burger,American,9.27,Weekend,Not given,34,30
221,1476696,231061,Han Dynasty,Chinese,33.03,Weekday,Not given,33,31
225,1476698,142461,Delicatessen,American,11.64,Weekend,Not given,27,27
229,1477794,127149,Sarabeth's East,American,9.41,Weekend,Not given,25,16
230,1477048,200074,Osteria Morini,Italian,9.07,Weekend,Not given,33,16
232,1476566,103884,S'MAC,American,14.46,Weekend,Not given,34,17
239,1476830,361509,Cafeteria,American,17.03,Weekend,Not given,34,20
242,1477603,399121,Blue Ribbon Sushi,Japanese,11.30,Weekday,Not given,24,24
246,1476849,42052,Pepe Rosso To Go,Italian,13.73,Weekend,Not given,21,28
248,1477679,120833,Bareburger,American,16.25,Weekend,Not given,29,15
249,1477810,94483,Bistango,Italian,24.20,Weekend,Not given,28,21
250,1477342,49631,The Meatball Shop,Italian,14.31,Weekend,Not given,23,17
251,1478133,114085,Blue Ribbon Sushi Bar & Grill,Japanese,19.40,Weekend,Not given,28,20
252,1477756,251607,Shake Shack,American,14.12,Weekday,Not given,31,28
253,1477721,72339,Donburi-ya,Japanese,14.70,Weekend,Not given,30,27
254,1476952,229946,Balthazar Boulangerie,French,15.52,Weekend,Not given,21,29
256,1478210,320493,Vanessa's Dumplings,Chinese,29.20,Weekday,Not given,27,30
260,1476819,104548,Tarallucci e Vino Restaurant,Italian,29.10,Weekday,Not given,28,33
264,1477909,47440,Blue Ribbon Fried Chicken,American,12.18,Weekend,Not given,31,23
266,1477286,110091,The Meatball Shop,Italian,12.18,Weekend,Not given,27,17
267,1478436,95164,Amma,Indian,17.03,Weekend,Not given,28,19
270,1476892,177078,Lantern Thai Kitchen,Thai,21.93,Weekday,Not given,22,25
276,1477273,95644,RedFarm Broadway,Chinese,12.61,Weekday,Not given,26,27
278,1477522,101084,RedFarm Hudson,Chinese,12.13,Weekend,Not given,20,22
280,1478295,117810,Momoya,Japanese,19.35,Weekday,Not given,29,24
281,1476551,49034,The Smile,American,12.18,Weekend,Not given,22,27
282,1476846,82041,Parm,Italian,22.80,Weekend,Not given,35,20
286,1476563,114085,Blue Ribbon Sushi Bar & Grill,Japanese,12.18,Weekend,Not given,24,18
288,1477348,298824,Bareburger,American,12.56,Weekend,Not given,24,26
289,1477525,52360,TAO,Japanese,24.30,Weekend,Not given,24,22
294,1477010,49631,The Meatball Shop,Italian,19.40,Weekend,Not given,28,17
296,1477908,378923,Vanessa's Dumpling House,Chinese,12.18,Weekend,Not given,27,18
298,1476728,250494,Bubby's,American,24.25,Weekend,Not given,34,28
299,1477815,144997,RedFarm Hudson,Chinese,32.93,Weekend,Not given,33,30
300,1477283,75115,RedFarm Hudson,Chinese,14.07,Weekday,Not given,20,32
305,1477729,355713,RedFarm Broadway,Chinese,14.26,Weekend,Not given,28,24
306,1477312,269793,Dirty Bird To Go (archived),American,8.54,Weekend,Not given,32,30
307,1476577,100778,The Meatball Shop,Italian,12.18,Weekend,Not given,25,28
314,1478229,64153,Blue Ribbon Fried Chicken,American,21.34,Weekend,Not given,35,23
315,1477270,314480,Shake Shack,American,6.79,Weekend,Not given,20,25
317,1476821,80434,Bareburger,American,12.18,Weekend,Not given,33,18
319,1477762,91397,Chipotle Mexican Grill $1.99 Delivery,Mexican,14.16,Weekday,Not given,22,24
320,1476906,237592,Shake Shack,American,5.68,Weekend,Not given,31,30
325,1476848,365401,Dirty Bird To Go (archived),American,15.57,Weekend,Not given,30,24
326,1477870,301032,Mission Cantina,Mexican,14.45,Weekend,Not given,27,29
327,1477714,100536,Shake Shack,American,8.15,Weekend,Not given,26,17
335,1476702,152786,Cafe Habana,Mexican,25.22,Weekday,Not given,32,28
339,1476773,92806,Shake Shack,American,12.18,Weekend,Not given,29,22
340,1478299,130521,Lucky's Famous Burgers,American,6.01,Weekend,Not given,33,16
341,1477326,52031,Han Dynasty,Chinese,21.93,Weekend,Not given,24,20
344,1477537,104130,Blue Ribbon Sushi,Japanese,15.76,Weekend,Not given,30,26
346,1478338,150865,Vanessa's Dumpling House,Chinese,5.72,Weekend,Not given,20,21
347,1477025,331608,Shake Shack,American,19.40,Weekend,Not given,30,18
348,1477158,363561,Shake Shack,American,8.49,Weekday,Not given,33,32
349,1477375,235620,Shake Shack,American,32.93,Weekend,Not given,32,25
350,1478316,118975,Shake Shack,American,12.23,Weekend,Not given,20,27
351,1476553,128224,Osteria Morini,Italian,9.17,Weekend,Not given,25,22
352,1478330,109419,The Meatball Shop,Italian,11.69,Weekend,Not given,30,21
354,1476569,55334,Sushi of Gari Tribeca,Japanese,9.85,Weekend,Not given,26,17
355,1477040,301618,Vanessa's Dumplings,Chinese,25.22,Weekday,Not given,32,24
362,1477339,68965,RedFarm Hudson,Chinese,12.18,Weekend,Not given,20,18
363,1477490,232035,ilili Restaurant,Middle Eastern,9.17,Weekend,Not given,26,19
364,1477135,62359,Pylos,Mediterranean,19.40,Weekend,Not given,28,29
365,1477931,403833,Room Service,Thai,6.69,Weekday,Not given,25,32
366,1477822,61588,Blue Ribbon Sushi,Japanese,5.82,Weekend,Not given,34,27
367,1477360,91907,Sarabeth's Restaurant,American,12.08,Weekend,Not given,28,26
371,1478315,235818,Shake Shack,American,12.13,Weekend,Not given,30,19
372,1476941,127149,Sarabeth's East,American,5.72,Weekend,Not given,33,26
377,1476897,197265,Hill Country Fried Chicken,Southern,29.15,Weekend,Not given,20,17
379,1477007,342882,Yama Japanese Restaurant,Japanese,5.82,Weekend,Not given,30,30
380,1477958,309981,Blue Ribbon Fried Chicken,American,29.10,Weekend,Not given,31,27
381,1478102,165695,The Smile,American,13.39,Weekend,Not given,20,16
383,1478252,94167,Dos Caminos,Mexican,22.36,Weekend,Not given,30,26
388,1478104,75722,Osteria Morini,Italian,24.25,Weekday,Not given,22,24
389,1478065,212326,RedFarm Broadway,Chinese,20.18,Weekday,Not given,30,26
392,1476580,331143,Waverly Diner,American,6.84,Weekend,Not given,24,18
394,1477192,374286,Vanessa's Dumpling House,Chinese,5.92,Weekday,Not given,30,32
397,1477919,75484,Five Guys Burgers and Fries,American,29.15,Weekend,Not given,20,16
398,1478120,47440,Blue Ribbon Fried Chicken,American,8.10,Weekend,Not given,33,22
400,1477806,195927,Boqueria,Spanish,12.66,Weekend,Not given,27,30
403,1477156,93797,ilili Restaurant,Middle Eastern,6.02,Weekday,Not given,27,29
409,1478047,127934,Blue Ribbon Fried Chicken,American,12.13,Weekend,Not given,20,26
414,1477620,148320,Tamarind TriBeCa,Indian,16.49,Weekday,Not given,31,28
416,1478422,197832,The Meatball Shop,Italian,14.84,Weekend,Not given,20,28
417,1477482,114919,Yama Japanese Restaurant,Japanese,25.27,Weekend,Not given,30,16
424,1477066,376381,Shake Shack,American,8.25,Weekend,Not given,30,15
425,1477914,366975,Blue Ribbon Sushi Bar & Grill,Japanese,16.39,Weekend,Not given,31,18
426,1478064,221430,Han Dynasty,Chinese,14.75,Weekend,Not given,30,16
428,1477410,39011,Mamoun's Falafel,Mediterranean,9.07,Weekend,Not given,20,24
432,1477737,104548,Tarallucci e Vino Restaurant,Italian,11.59,Weekend,Not given,21,15
433,1477058,65779,The Kati Roll Company,Indian,24.35,Weekday,Not given,33,29
436,1476596,199735,The Meatball Shop,Italian,14.12,Weekend,Not given,32,18
438,1478278,42755,Blue Ribbon Fried Chicken,American,13.00,Weekend,Not given,29,30
440,1476557,348787,Otto Enoteca Pizzeria,Italian,16.15,Weekend,Not given,35,22
441,1477264,35774,The Meatball Shop,Italian,12.23,Weekday,Not given,28,33
442,1476806,203370,Chipotle Mexican Grill $1.99 Delivery,Mexican,24.30,Weekday,Not given,21,33
443,1478000,167136,ilili Restaurant,Middle Eastern,29.05,Weekend,Not given,24,29
448,1477458,114247,Shake Shack,American,20.23,Weekend,Not given,32,18
450,1477772,91958,TAO,Japanese,12.18,Weekday,Not given,26,33
451,1477319,145389,Westville Hudson,American,20.23,Weekday,Not given,31,29
453,1477571,121476,Blue Ribbon Fried Chicken,American,16.20,Weekend,Not given,32,23
454,1477274,96877,Melt Shop,American,9.12,Weekday,Not given,29,33
455,1477276,304449,Friend of a Farmer,American,9.75,Weekend,Not given,26,30
459,1478267,93065,Han Dynasty,Chinese,14.16,Weekend,Not given,30,23
464,1477600,347263,Hangawi,Korean,6.74,Weekend,Not given,21,22
466,1477498,103500,RedFarm Hudson,Chinese,14.02,Weekend,Not given,29,22
470,1477126,41409,Nobu Next Door,Japanese,15.76,Weekday,Not given,33,31
472,1476586,173667,Osteria Morini,Italian,8.88,Weekend,Not given,34,26
473,1477951,242689,The Odeon,American,13.92,Weekend,Not given,34,23
475,1476738,233614,Yama 49,Japanese,22.36,Weekend,Not given,33,25
476,1477445,97079,Donburi-ya,Japanese,5.77,Weekend,Not given,27,29
480,1476877,53289,The Loop,Japanese,4.66,Weekend,Not given,34,25
483,1477936,133202,Blue Ribbon Sushi,Japanese,9.17,Weekend,Not given,27,29
484,1478209,63141,Shake Shack,American,29.10,Weekend,Not given,23,28
486,1477809,148499,Posto,Italian,24.25,Weekend,Not given,23,25
488,1477516,52256,Han Dynasty,Chinese,29.15,Weekend,Not given,31,19
493,1477521,113972,RedFarm Hudson,Chinese,12.08,Weekday,Not given,21,26
496,1477929,87006,Nobu Next Door,Japanese,6.74,Weekend,Not given,31,29
498,1476866,42018,Blue Ribbon Sushi,Japanese,12.18,Weekday,Not given,34,32
500,1477495,92806,Shake Shack,American,14.94,Weekday,Not given,33,31
503,1477238,87727,Blue Ribbon Sushi,Japanese,13.87,Weekend,Not given,28,28
508,1477659,54093,Shake Shack,American,13.00,Weekend,Not given,20,18
509,1477661,122852,Blue Ribbon Fried Chicken,American,24.20,Weekend,Not given,28,29
511,1476624,117810,Momoya,Japanese,6.84,Weekday,Not given,21,24
512,1477832,100778,Spice Thai,Thai,15.86,Weekend,Not given,34,25
514,1478037,97346,da Umberto,Italian,7.61,Weekend,Not given,23,26
515,1477109,208020,Sushi of Gari 46,Japanese,29.05,Weekend,Not given,21,23
516,1476902,165110,Room Service,Thai,22.31,Weekend,Not given,22,15
518,1476703,405334,TAO,Japanese,25.22,Weekend,Not given,26,16
522,1477371,369452,UVA Wine Bar & Restaurant,Italian,29.15,Weekend,Not given,29,30
525,1476954,97370,Momoya,Japanese,14.21,Weekend,Not given,24,30
530,1478114,237616,Shake Shack,American,5.68,Weekend,Not given,26,18
537,1476929,61181,S'MAC,American,24.20,Weekend,Not given,28,17
539,1477210,182080,Shake Shack,American,14.65,Weekday,Not given,26,33
541,1477858,60052,Rubirosa,Italian,5.77,Weekend,Not given,27,21
542,1477788,270444,P.J. Clarke's,American,4.71,Weekend,Not given,23,15
543,1476711,106968,Blue Ribbon Fried Chicken,American,8.78,Weekend,Not given,22,26
547,1476895,105460,Burger Joint,American,13.10,Weekend,Not given,22,18
549,1476628,70456,Parm,Italian,12.56,Weekday,Not given,32,28
550,1476927,62626,Sushi of Gari 46,Japanese,13.05,Weekend,Not given,24,22
551,1477547,242754,Rubirosa,Italian,13.92,Weekend,Not given,29,27
552,1478349,229946,Balthazar Boulangerie,French,21.39,Weekend,Not given,35,29
553,1477850,216438,Blue Ribbon Sushi,Japanese,29.25,Weekend,Not given,33,17
555,1477133,175290,Shake Shack,American,12.18,Weekend,Not given,26,25
557,1477724,80531,RedFarm Hudson,Chinese,12.18,Weekend,Not given,24,27
559,1478292,334373,Tamarind TriBeCa,Indian,12.18,Weekend,Not given,26,30
560,1478024,241719,Sushi of Gari Tribeca,Japanese,14.12,Weekend,Not given,21,29
563,1476898,174437,Han Dynasty,Chinese,29.20,Weekend,Not given,26,30
564,1477285,325285,RedFarm Broadway,Chinese,14.02,Weekday,Not given,25,26
569,1477657,177078,Lantern Thai Kitchen,Thai,13.97,Weekend,Not given,28,29
574,1478059,53947,Gaia Italian Cafe,Italian,8.78,Weekend,Not given,25,15
576,1477743,104130,Blue Ribbon Sushi,Japanese,6.64,Weekend,Not given,23,15
581,1477321,89844,Five Guys Burgers and Fries,American,12.08,Weekend,Not given,20,18
582,1477322,355592,CafÌ© China,Chinese,12.13,Weekend,Not given,27,25
585,1478303,72639,Sushi of Gari,Japanese,10.72,Weekday,Not given,30,26
586,1476647,294246,Piccolo Angolo,Italian,19.35,Weekend,Not given,29,29
593,1476717,151191,Pongsri Thai,Thai,20.18,Weekday,Not given,23,25
595,1478063,367093,Parm,Italian,15.86,Weekday,Not given,30,24
597,1477763,111356,Blue Ribbon Sushi,Japanese,13.87,Weekday,Not given,31,30
600,1478357,142356,Blue Ribbon Sushi,Japanese,14.07,Weekday,Not given,35,29
601,1478055,7567,indikitch,Indian,5.58,Weekend,Not given,35,30
604,1477159,283310,Shake Shack,American,8.73,Weekend,Not given,35,17
607,1476747,115213,Junoon,Indian,9.22,Weekday,Not given,30,32
608,1477165,128600,Blue Ribbon Fried Chicken,American,15.33,Weekend,Not given,23,15
609,1477378,115610,Tamarind TriBeCa,Indian,12.13,Weekend,Not given,35,20
610,1476803,73873,Han Dynasty,Chinese,14.02,Weekend,Not given,24,15
611,1477792,270525,The Smile,American,8.39,Weekday,Not given,20,31
615,1477623,41136,The Meatball Shop,Italian,19.35,Weekend,Not given,27,20
616,1477098,304509,RedFarm Broadway,Chinese,22.80,Weekday,Not given,33,33
617,1477399,378482,Shake Shack,American,29.49,Weekend,Not given,34,24
618,1476649,38116,Ravagh Persian Grill,Middle Eastern,16.93,Weekend,Not given,33,21
619,1478288,58231,Rohm Thai,Thai,29.10,Weekend,Not given,31,23
623,1476637,49695,Blue Ribbon Fried Chicken,American,18.24,Weekend,Not given,21,16
625,1478222,370656,Vanessa's Dumplings,Chinese,8.98,Weekend,Not given,20,20
626,1476774,114400,Shake Shack,American,29.39,Weekday,Not given,23,33
632,1478265,52832,Dos Caminos,Mexican,16.06,Weekend,Not given,35,19
633,1476625,348352,Olea,Mediterranean,6.69,Weekday,Not given,20,28
634,1477413,325272,Shake Shack,American,16.10,Weekend,Not given,28,24
636,1476708,126026,Nobu Next Door,Japanese,9.51,Weekend,Not given,25,29
637,1477168,352130,TAO,Japanese,12.08,Weekend,Not given,24,30
638,1476872,42018,Blue Ribbon Sushi,Japanese,5.82,Weekday,Not given,27,28
639,1477161,263426,Nobu Next Door,Japanese,9.41,Weekend,Not given,32,30
640,1477799,399520,Xe May Sandwich Shop,Vietnamese,14.07,Weekday,Not given,28,28
642,1478132,74762,Cafeteria,American,12.23,Weekday,Not given,26,25
643,1477456,124085,Blue Ribbon Sushi Bar & Grill,Japanese,15.91,Weekend,Not given,31,16
646,1477359,373285,RedFarm Hudson,Chinese,12.08,Weekend,Not given,21,24
647,1477542,59673,Shake Shack,American,12.08,Weekday,Not given,27,27

In [57]:
# Write the code here
len(df[df["rating"] == "Not given"])

736

#### Observations:

### Exploratory Data Analysis (EDA)

### Univariate Analysis

### **Question 6:** Explore all the variables and provide observations on their distributions. (Generally, histograms, boxplots, countplots, etc. are used for univariate exploration.) [9 marks]

In [ ]:
# Write the code here
import matplotlib.pyplot as plt
import numpy as np  

xpoints = df["food_preparation_time"]
ypoints = df["rating"]
plt.plot(xpoints, ypoints)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

### **Question 7**: Which are the top 5 restaurants in terms of the number of orders received? [1 mark]

In [ ]:
# Write the code here

#### Observations:

### **Question 8**: Which is the most popular cuisine on weekends? [1 mark]

In [ ]:
# Write the code here

#### Observations:

### **Question 9**: What percentage of the orders cost more than 20 dollars? [2 marks]

In [ ]:
# Write the code here

#### Observations:

### **Question 10**: What is the mean order delivery time? [1 mark]

In [ ]:
# Write the code here

#### Observations:

### **Question 11:** The company has decided to give 20% discount vouchers to the top 3 most frequent customers. Find the IDs of these customers and the number of orders they placed. [1 mark]

In [ ]:
# Write the code here

#### Observations:

### Multivariate Analysis

### **Question 12**: Perform a multivariate analysis to explore relationships between the important variables in the dataset. (It is a good idea to explore relations between numerical variables as well as relations between numerical and categorical variables) [10 marks]

In [ ]:
# Write the code here

### **Question 13:** The company wants to provide a promotional offer in the advertisement of the restaurants. The condition to get the offer is that the restaurants must have a rating count of more than 50 and the average rating should be greater than 4. Find the restaurants fulfilling the criteria to get the promotional offer. [3 marks]

In [ ]:
# Write the code here

#### Observations:

### **Question 14:** The company charges the restaurant 25% on the orders having cost greater than 20 dollars and 15% on the orders having cost greater than 5 dollars. Find the net revenue generated by the company across all orders. [3 marks]

In [ ]:
# Write the code here

#### Observations:

### **Question 15:** The company wants to analyze the total time required to deliver the food. What percentage of orders take more than 60 minutes to get delivered from the time the order is placed? (The food has to be prepared and then delivered.) [2 marks]

In [ ]:
# Write the code here

#### Observations:

### **Question 16:** The company wants to analyze the delivery time of the orders on weekdays and weekends. How does the mean delivery time vary during weekdays and weekends? [2 marks]

In [ ]:
# Write the code here

#### Observations:

### Conclusion and Recommendations

### **Question 17:** What are your conclusions from the analysis? What recommendations would you like to share to help improve the business? (You can use cuisine type and feedback ratings to drive your business recommendations.) [6 marks]

### Conclusions:
*

### Recommendations:

*

---